Github-integration
polkassembly/fellowship pull request #28
Opened 2024-07-30 05:40 UTC by adetoye-dev

2024-07-31 17:42 UTC, alphainfinitus requested changes
There's a heavy use of `any` in the PR, please assign types instead

2024-07-31 17:42 UTC, alphainfinitus commented on src/app/api/v1/github/getGithubMonthlyStats.ts
> +	const currentDate = new Date();
we should use dayjs instead of dealing with dates in javascript directly, please import from `dayjs-init.ts` file

2024-07-31 17:42 UTC, alphainfinitus commented on src/components/Profile/Socials/index.tsx
> +	console.log('ProfileSocials -> socialLinks', links);
please remove any console logs

2024-07-31 17:42 UTC, alphainfinitus commented on src/components/Profile/Activity/ContributionGraph.tsx
> +		if (count === 0) return 'fill-contributionEmpty';
return these colours by reading from Theme colours files instead, so that if that changes, the build fails too

2024-07-31 17:42 UTC, alphainfinitus commented on src/app/api/v1/github/getGithubMonthlyStats.ts
this is not a valid api route, the route file should be named route.ts

2024-07-31 17:42 UTC, alphainfinitus commented on src/app/api/v1/github/getUserCommitHistory.ts
this is not a valid api route, the route file should be named route.ts

2024-07-31 17:42 UTC, alphainfinitus commented on src/app/api/v1/github/getGithubMonthlyStats.ts
> +		fetch(`https://api.github.com/repos/${FELLOWS_REPO}/commits?per_page=100&since=${currentMonthFirstDay.toISOString()}&until=${currentMonthLastDay.toISOString()}`).then((res) =>
please see if any of these responses from github can be cached, we don't want to be hitting the rate limit

2024-07-31 17:42 UTC, alphainfinitus commented on src/components/Profile/Activity/ContributionGraph.tsx
> +import { getUserCommitHistory } from '@/app/api/v1/github/getUserCommitHistory';
please don't import from `api/v1/` into client side, unless it's a fetch call to our own api

2024-07-31 17:42 UTC, alphainfinitus commented on src/components/Profile/Activity/ContributionGraph.tsx
> +	lastYear.setFullYear(today.getFullYear() - 1);
please use day js instead

2024-07-31 17:42 UTC, alphainfinitus commented on src/components/Profile/Activity/ContributionGraph.tsx
> +	function formatContributionDate(day: { date: string; count: number; color: string }) {
a lot of these functions can be made into utils, so that the React component doesn't look too messy

2024-08-06 06:20 UTC, adetoye-dev commented on src/components/Profile/Activity/ContributionGraph.tsx
> +		if (count === 0) return 'fill-contributionEmpty';
It doesn't render correctly for dark mode when I do.

2024-08-12 09:24 UTC, merged